### ISSUE TITLE
Curation reward links are broken on activity page

### ISSUE THREAD

**Issue by anilkilic** [emre/steemrocks#18]
![screen shot 2018-01-15 at 21 48 43](https://user-images.githubusercontent.com/2311397/34957295-0fa18098-fa3e-11e7-92ab-223ab702cfe1.png)

You can check it on your profile,
http://steem.rocks/@emrebeyler any link under *curation reward*.

macOS & Safari

**Comment by emre** [comment]
yeah, this is a known issue but I'm just too lazy to fix it. thank you for the report, will do the fix as soon as possible.

**Comment by emre** [comment]
Fixed and deployed. Thanks for the contribution!
