### ISSUE TITLE
Incoming delegation page on steem.rocks not using correct URL

### ISSUE THREAD

**Issue by amosbastian** [emre/steemrocks#21]
I was checking my feed just now and saw @emrebeyler [added incoming delegations](https://steemit.com/steemrocks/@emrebeyler/incoming-delegation-information-on-steem-rocks) to steem.rocks, so I went to check it out. After checking out some people's incoming delegations I wanted to see the account they were receiving it from, so I clicked on it and realised it's not working properly. It does work on the outdoing delegation page, so it should be an easy fix for @emrebeyler.

#### Expected behavior
When you click on the username of the person sending the delegation you expect to be brought to their page on Steemit.

#### Actual behavior
Clicking on the username takes you to https://steemit.com/@ instead of https://steemit.com/@{username}, an example is shown below:

<center>![incoming_delegation.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516189157/qhpk02dcnna6jquqxlqd.png)
</center>

<center>![error.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516189163/gg0skjw5bcnyjkow2jgl.png)
</center>

#### How to reproduce
Go to steem.rocks, find someone with incoming delegations and go to their incoming delegation page, e.g. http://steem.rocks/emrebeyler/delegations/in, then click on the username of one of the people sending incoming delegations.

* Browser: Chrome
* Operating system: Ubuntu 16.04

#### Recording of the bug

![Peek 2018-01-17 12-01v2.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1516190580/lqbgpaahaarnu4ztn6x7.gif)

#### Extra information

I checked the steem.rocks' GitHub and it seems that something is either going wrong in [app.py](https://github.com/emre/steemrocks/blob/master/steemrocks/app.py) (more than likely here) or the HTML page [incoming_delegations.html](https://github.com/emre/steemrocks/blob/master/steemrocks/templates/incoming_delegations.html).
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@amosbastian/incoming-delegation-page-on-steem-rocks-not-using-correct-url">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by crokkon** [comment]
fixed with https://github.com/emre/steemrocks/commit/2e92115b4c02b03f23ed4089c021c708ae770aec
